version: "3.7"

services:
  api:
    build:
      context: services/api
      dockerfile: Dockerfile
    ports:
      - 8081:80

  frontend:
    build:
      context: services/frontend
      dockerfile: Dockerfile.nginx
    ports:
      - 8082:80

  site:
    build:
      context: services/site
      dockerfile: Dockerfile
    ports:
      - 8083:80

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/proxy/index.html:/usr/share/nginx/html/index.html
    ports:
      - 8080:80
    depends_on:
      - api
      - site
      - frontend
