version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.npm
    ports:
      - 8080:3000
    volumes:
      - ${PWD}/src/App.js:/app/src/App.js
      - ${PWD}/src/index.js:/app/src/index.js
    stdin_open: true
    command: ["npm", "start"]
