ARG BUILD_IMAGE
# Build static site with dev image as base
FROM ${BUILD_IMAGE} as builder

RUN npm ci --silent

COPY src/ src/

RUN npm run build

# Final image with built artifact copied from builder image
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html

COPY etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]